require.config({
	paths:{
		'jquery':'jquery-3.2.1.min',
		'setRem':'setRem',
		'pageLoad':'pageLoad'
	}
});
require(['jquery','setRem','pageLoad'],function($,setRem,pg){
	/*设置html的font-size*/
	setRem();
	/**/
	if(!localStorage.getItem('signSuccessFP')){	
		pg.dsOpenLoading._show('正在签到').imgLoadedHide();
	}else{
		pg.dsOpenLoading.imgLoadedHide();
	}
	/**/
	localStorage.setItem('signSuccessFP','start');
});